version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
     - 5432:5432
    env_file:
      - ".env"
    volumes:
     - go_auth:/var/lib/postgresql/data
    networks:
      - auth_networks

  core:
    container_name: core
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    env_file:
     - ".env"
    ports:
      - 8080:8080
    networks:
      - auth_networks

networks:
  auth_networks:
    driver: bridge

volumes:
  go_auth: