version: "3"

services:
  test_db:
    image: postgres:latest
    container_name: test_postgres
    ports:
      - 5432:5432
    env_file:
      - ".env"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d